version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: dumbdee-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password123}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-dumbdee}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - dumbdee-network

  # Redis Cache (optional)
  redis:
    image: redis:7-alpine
    container_name: dumbdee-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dumbdee-network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: dumbdee-backend
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: 3001
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/dumbdee?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key}
      AWS_REGION: ${AWS_REGION:-us-east-1}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME:-dumbdee-images}
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      PAYPAL_CLIENT_SECRET: ${PAYPAL_CLIENT_SECRET}
      RAZORPAY_KEY_ID: ${RAZORPAY_KEY_ID}
      RAZORPAY_KEY_SECRET: ${RAZORPAY_KEY_SECRET}
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - dumbdee-network

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: dumbdee-frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_BASE_URL: http://localhost:3001/api
      REACT_APP_AWS_REGION: ${AWS_REGION:-us-east-1}
      REACT_APP_S3_BUCKET_NAME: ${S3_BUCKET_NAME:-dumbdee-images}
      REACT_APP_PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      REACT_APP_RAZORPAY_KEY_ID: ${RAZORPAY_KEY_ID}
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - dumbdee-network

  # Nginx Reverse Proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: dumbdee-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - dumbdee-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  dumbdee-network:
    driver: bridge

